"""Export original local examples through the production comparison engine.

No network access, captured dates, recurrence claims, or historical study inputs.
Run normally to regenerate; --check rejects missing, stale, or legacy served data.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from skillvariants.comparison import compare_documents
from skillvariants.parser import parse_skill_md


def build_examples(root: Path = ROOT) -> dict:
    folder = root / "examples" / "approval-gate"
    catalog = json.loads((folder / "catalog.json").read_text(encoding="utf-8"))
    examples = []
    seen = set()
    for entry in catalog["examples"]:
        case_id = entry["id"]
        if not case_id.isascii() or not case_id.replace("-", "").isalnum() or case_id in seen:
            raise ValueError(f"invalid or duplicate example id: {case_id!r}")
        seen.add(case_id)
        docs, sources = [], {}
        for side, role in (("a", "target"), ("b", "variant")):
            path = folder / case_id / role / "SKILL.md"
            raw = path.read_bytes().decode("utf-8")
            relative = path.relative_to(root).as_posix()
            doc = parse_skill_md(raw)
            doc.source_metadata = {"path": relative, "kind": "original_illustrative_example"}
            docs.append(doc)
            sources[side] = {"label": role.capitalize(), "path": relative, "content": raw}
        comparison = compare_documents(*docs)
        if comparison["truncation"]["truncated"]:
            raise ValueError(f"example {case_id}: evidence was truncated; shorten the original example")
        for side in sources:
            sources[side]["raw_sha256"] = comparison["sources"][side]["raw_sha256"]
        hunks = {h["hunk_id"]: h for h in comparison["hunks"]}
        for citation in entry["citations"]:
            if citation["hunk_id"] not in hunks:
                raise ValueError(f"example {case_id}: cited hunk does not exist")
            hunk = hunks[citation["hunk_id"]]
            for side in ("a", "b"):
                valid = {line["line_number"] for line in hunk[side]["lines"]}
                if not citation[f"{side}_lines"] or not set(citation[f"{side}_lines"]) <= valid:
                    raise ValueError(f"example {case_id}: citation outside {side} hunk lines")
        examples.append({**entry, "sources": sources, "comparison": comparison})
    return {
        "schema_version": "2",
        "provenance": {
            "kind": "original_illustrative_examples",
            "label": "Original illustrative examples",
            "description": "Authored locally to demonstrate comparison. These are not sampled GitHub adaptations or evidence of adoption.",
            "method": "Diffs, source hashes and paired hunks are generated by skillvariants.comparison.compare_documents. Observations and interpretations are editorial annotations, not automated semantic judgments.",
        },
        "examples": examples,
    }


def serialized_examples(root: Path = ROOT) -> str:
    return json.dumps(build_examples(root), indent=2, ensure_ascii=False) + "\n"


def check_export(root: Path = ROOT, destination: Path | None = None) -> bool:
    destination = destination or root / "web" / "data" / "examples.json"
    if not destination.is_file():
        return False
    if destination.read_bytes() != serialized_examples(root).encode("utf-8"):
        return False
    return not any(p.name != "examples.json" for p in destination.parent.glob("*.json"))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the offline export is missing or stale")
    args = parser.parse_args(argv)
    out = ROOT / "web" / "data" / "examples.json"
    if args.check:
        if not check_export(ROOT, out):
            print("Example export is stale, missing, or contains legacy data. Run python scripts/export_web_data.py and remove legacy web/data JSON files.", file=sys.stderr)
            return 1
        print("Example export is current and contains only original illustrative cases.")
        return 0
    payload = serialized_examples(ROOT)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(payload.encode("utf-8"))
    print(f"Wrote {out.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
